language: objective-c
install:
  - sudo easy_install cpp-coveralls
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
script:
  - bundle exec rake test
after_success:
  - ./Script/coveralls.sh
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
